---
- name: Query Primary IP for device role "{{ nb_device_role }}"
  vars:
    device_role: "{{ nb_device_role }}"
  set_fact:
    query_string: |
      query {
        virtual_machines(role: "{{ nb_device_role }}", status: "active", has_primary_ip: true) {
          name
          primary_ip4 {
            address
          }
        }
      }
- name: Nautobot - Get all devices of role type "{{ nb_device_role }}"
  set_fact:
    query_response: "{{ query('networktocode.nautobot.lookup_graphql', query_string,
                    url='{{ nautobot_url }}',
                    token='{{ nautobot_token }}',
                    validate_certs=false) }}"